name: deerstalkers
favicon: null
layout_spectrum: 0
typography_spectrum: 0.36842
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#464124'
    - '#7b743e'
    - '#1f1514'
    - '#a1995a'
    - '#cbb59e'
  brandStrength: 0.4375
  lightness: 0.039938684552907944
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
